"""empty message

Revision ID: 5f2163d18a55
Revises: a4649a5464b6
Create Date: 2019-11-19 22:17:14.178624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2163d18a55'
down_revision = 'a4649a5464b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('allowedinside', sa.Boolean(create_constraint=5), nullable=True))
    op.add_column('location', sa.Column('allowedoutside', sa.Boolean(create_constraint=5), nullable=True))
    op.add_column('location', sa.Column('bathrooms', sa.Boolean(create_constraint=5), nullable=True))
    op.add_column('location', sa.Column('locationtype', sa.String(length=12), nullable=False))
    op.add_column('location', sa.Column('mealsavailable', sa.Boolean(create_constraint=5), nullable=True))
    op.add_column('location', sa.Column('smalldogarea', sa.Boolean(create_constraint=5), nullable=True))
    op.add_column('location', sa.Column('wateravailable', sa.Boolean(create_constraint=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'wateravailable')
    op.drop_column('location', 'smalldogarea')
    op.drop_column('location', 'mealsavailable')
    op.drop_column('location', 'locationtype')
    op.drop_column('location', 'bathrooms')
    op.drop_column('location', 'allowedoutside')
    op.drop_column('location', 'allowedinside')
    # ### end Alembic commands ###
